import Foundation

enum MapChartTemplateOverrides {
    // Canonical path overrides derived from mapchartSave_allCountiesMaster.txt.
    // Key format: us-<state>-<normalized county name>
    static let pathByCountyKey: [String: String] = [
        "us-al-st clair": "St__Clair__AL",
        "us-ar-st francis": "St__Francis__AR",
        "us-as-manu a": "Manuʻa__AS",
        "us-dc-district of columbia": "Washington__DC",
        "us-fl-st johns": "St__Johns__FL",
        "us-fl-st lucie": "St__Lucie__FL",
        "us-il-st clair": "St__Clair__IL",
        "us-in-st joseph": "St__Joseph__IN",
        "us-la-st bernard": "St__Bernard__LA",
        "us-la-st charles": "St__Charles__LA",
        "us-la-st helena": "St__Helena__LA",
        "us-la-st james": "St__James__LA",
        "us-la-st john the baptist": "St__John_the_Baptist__LA",
        "us-la-st landry": "St__Landry__LA",
        "us-la-st martin": "St__Martin__LA",
        "us-la-st mary": "St__Mary__LA",
        "us-la-st tammany": "St__Tammany__LA",
        "us-md-baltimore": "Baltimore_County__MD",
        "us-mi-st clair": "St__Clair__MI",
        "us-mi-st joseph": "St__Joseph__MI",
        "us-mn-st louis": "St__Louis__MN",
        "us-mo-st charles": "St__Charles__MO",
        "us-mo-st clair": "St__Clair__MO",
        "us-mo-st francois": "St__Francois__MO",
        "us-mo-st louis": "St__Louis_Co___MO",
        "us-mo-st louis city": "St__Louis__MO",
        "us-ny-st lawrence": "St__Lawrence__NY",
        "us-pr-anasco": "Añasco__PR",
        "us-pr-bayamon": "Bayamón__PR",
        "us-pr-canovanas": "Canóvanas__PR",
        "us-pr-catano": "Cataño__PR",
        "us-pr-comerio": "Comerío__PR",
        "us-pr-guanica": "Guánica__PR",
        "us-pr-juana diaz": "Juana_Díaz__PR",
        "us-pr-las marias": "Las_Marías__PR",
        "us-pr-loiza": "Loíza__PR",
        "us-pr-manati": "Manatí__PR",
        "us-pr-mayaguez": "Mayagüez__PR",
        "us-pr-penuelas": "Peñuelas__PR",
        "us-pr-rincon": "Rincón__PR",
        "us-pr-rio grande": "Río_Grande__PR",
        "us-pr-san german": "San_Germán__PR",
        "us-pr-san sebastian": "San_Sebastián__PR",
        "us-va-bedford": "Bedford_Co___VA",
        "us-va-fairfax": "Fairfax_Co___VA",
        "us-va-fairfax city": "Fairfax__VA",
        "us-va-franklin": "Franklin_Co___VA",
        "us-va-franklin city": "Franklin__VA",
        "us-va-richmond": "Richmond_Co___VA",
        "us-va-richmond city": "Richmond__VA",
        "us-va-roanoke": "Roanoke_Co___VA",
        "us-va-roanoke city": "Roanoke__VA",
        "us-wi-st croix": "St__Croix__WI",
    ]
}
