default_platform(:ios)

platform :ios do
  desc "Take screenshots for App Store using Snapshot"
  lane :snapshot do
    snapshot(
      scheme: "CountyTracker",
      output_directory: "~/Downloads/CountyTrackerScreenshots",
      clean: true
    )
  end
end
